version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    expose:
      - 25672:5672
      - 35672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

