name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0       # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install --upgrade pip click==8.0.1 colorama==0.4.4 future==0.18.2 gitdb==4.0.7 GitPython==3.1.17 htmlmin==0.1.12 Jinja2==3.0.1 joblib==1.0.1 jsmin==2.2.2 livereload==2.6.3 lunr==0.5.8 Markdown==3.3.4 MarkupSafe==2.0.1 mkdocs==1.1.2 mkdocs-git-revision-date-plugin==0.3.1 mkdocs-material==7.1.5 mkdocs-material-extensions==1.0.1 mkdocs-minify-plugin==0.4.0 nltk==3.6.2 Pygments==2.9.0 pymdown-extensions==8.2 PyYAML==5.4.1 regex==2021.4.4 six==1.16.0 smmap==4.0.0 tornado==6.1 tqdm==4.60.0 mkdocs-markdownextradata-plugin==0.2.4 mkdocs-redirects==1.0.3 mkdocs-markmap==2.1.0 mkdocs-table-reader-plugin==0.6
      - name: Build site
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
